### ISSUE TITLE
BankAccountSubscription not getting a GraphQLWebSocketContext

### ISSUE THREAD

**Issue by apo1967** [philip-jvm/learn-spring-boot-graphql#10]
Hi Philip, 

first of all maximum kudos for your great series, it's imho the best resource on Spring Boot with GraphQL around.

So, for our project we just tried to use the subscription authorization implementation of your project. Our goal is to handle multitenancy awareness of subscriptions.

Everything with the subscription works fine, so we can grab whatever we pass in as params when establishing the ws connection and save that to the `SubscriptionSession`. However when trying to fetch context params in the subscription resolver when calling  
`GraphQLWebSocketContext context = getContext(e);`
in `BankAccountSubscription.bankAccount(UUID id, DataFetchingEnvironment e)` you'll get a `ClassCastException`.
The reason is that it's giving you an instance of `GraphQLServletContext` instead of a `GraphQLWebSocketContext`.

When debugging your project (no changes at all except added cors handling in the filter chain) it shows the same behaviour. I wonder how this can be since everything works out fine in your video. Since I did change nothing in the code I have no explanation why it's not working. Can you (or anybody else) reproduce that and/or give me any hint what's wrong?

Tested with Chrome v. 94.0.4606.71 and the GraphQL Playground extension (same that you use in your videos) on Mac OS X Big Sur 11.6.

Thanks in advance for any help on this.

**Comment by apo1967** [comment]
My bad, I just missed out the fact that you are using the built-in playground from the app instead of the general extension. So now everything just works out as in your video. Just close this one.

**Comment by philip-jvm** [comment]
Thank you for your kind words Alexander. I'm glad you found a solution
