### ISSUE TITLE
Can help me Multiple DataLoaderRegistry

### ISSUE THREAD

**Issue by krdk01** [philip-jvm/learn-spring-boot-graphql#3]
Hi Philip,
Thanks for your youtube videos series.  They helped me to understand graphql. 

I am struggling about dataloader registry. In my project I want to register multiple data loader registry. How can I do that.  
In  [CustomGraphQLContextBuilder](https://github.com/philip-jvm/learn-spring-boot-graphql/blob/master/src/main/java/com/learn/graphql/context/CustomGraphQLContextBuilder.java); I can only register one factory.  I want to do it for multiple.

Thank you

**Comment by philip-jvm** [comment]
Hey Thrkrdk, 

I'm glad you enjoyed the videos :) 

It is currently not possible to register multiple data loader registries. 
Each graphql execution will have a single `GraphQLContext`. The GraphQLContext interface returns a single `DataLoaderRegistry`.
This should be sufficient as the data loader registry can contain 1-n dataloaders, each with their own implementation.

What is your user case for requiring multiple data loader registries in an execution? 
Perhaps there will be more value added having this discussion on the spring boot graphql github. That way you can discuss with the library developers and other engineers involved in the ecosystem.

Thanks
