### ISSUE TITLE
Interested in adding your Tutorial Playlist to the Kickstart website?

### ISSUE THREAD

**Issue by setchy** [philip-jvm/learn-spring-boot-graphql#6]
Hi Philip, great material on https://www.youtube.com/playlist?list=PLiwhu8iLxKwL1TU0RMM6z7TtkyW-3-5Wi

Would you be open to the idea of having your Tutorial series referenced on https://www.graphql-java-kickstart.com/

**Comment by philip-jvm** [comment]
Hey Adam,

Thanks a lot :)

Yeah, that would be cool if its referenced on the website or GitHub etc. Much appreciated. 

My goal is to keep the series up-to-date with new features, so hopefully it won’t get stale.

Cheers!

**Comment by setchy** [comment]
Awesome @philip-jvm!  I know a lot of the engineers at my organization have really enjoyed them.

We've released a new version of the https://www.graphql-java-kickstart.com site today.  Feel free to provide any feedback to Tutorials section ;)  https://www.graphql-java-kickstart.com/tutorials/
